/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantsIndexRouteImport } from './routes/plants.index'
import { Route as CatalogIndexRouteImport } from './routes/catalog.index'
import { Route as PlantsNewRouteImport } from './routes/plants.new'
import { Route as PlantsPlantidRouteImport } from './routes/plants.$plantid'
import { Route as CatalogNewRouteImport } from './routes/catalog.new'
import { Route as CatalogPlantdefidRouteImport } from './routes/catalog.$plantdefid'
import { Route as PlantsPlantidEditRouteImport } from './routes/plants.$plantid.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsIndexRoute = PlantsIndexRouteImport.update({
  id: '/plants/',
  path: '/plants/',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogIndexRoute = CatalogIndexRouteImport.update({
  id: '/catalog/',
  path: '/catalog/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsNewRoute = PlantsNewRouteImport.update({
  id: '/plants/new',
  path: '/plants/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsPlantidRoute = PlantsPlantidRouteImport.update({
  id: '/plants/$plantid',
  path: '/plants/$plantid',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogNewRoute = CatalogNewRouteImport.update({
  id: '/catalog/new',
  path: '/catalog/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogPlantdefidRoute = CatalogPlantdefidRouteImport.update({
  id: '/catalog/$plantdefid',
  path: '/catalog/$plantdefid',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsPlantidEditRoute = PlantsPlantidEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => PlantsPlantidRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/catalog/$plantdefid': typeof CatalogPlantdefidRoute
  '/catalog/new': typeof CatalogNewRoute
  '/plants/$plantid': typeof PlantsPlantidRouteWithChildren
  '/plants/new': typeof PlantsNewRoute
  '/catalog/': typeof CatalogIndexRoute
  '/plants/': typeof PlantsIndexRoute
  '/plants/$plantid/edit': typeof PlantsPlantidEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/catalog/$plantdefid': typeof CatalogPlantdefidRoute
  '/catalog/new': typeof CatalogNewRoute
  '/plants/$plantid': typeof PlantsPlantidRouteWithChildren
  '/plants/new': typeof PlantsNewRoute
  '/catalog': typeof CatalogIndexRoute
  '/plants': typeof PlantsIndexRoute
  '/plants/$plantid/edit': typeof PlantsPlantidEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/catalog/$plantdefid': typeof CatalogPlantdefidRoute
  '/catalog/new': typeof CatalogNewRoute
  '/plants/$plantid': typeof PlantsPlantidRouteWithChildren
  '/plants/new': typeof PlantsNewRoute
  '/catalog/': typeof CatalogIndexRoute
  '/plants/': typeof PlantsIndexRoute
  '/plants/$plantid/edit': typeof PlantsPlantidEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/catalog/$plantdefid'
    | '/catalog/new'
    | '/plants/$plantid'
    | '/plants/new'
    | '/catalog/'
    | '/plants/'
    | '/plants/$plantid/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/catalog/$plantdefid'
    | '/catalog/new'
    | '/plants/$plantid'
    | '/plants/new'
    | '/catalog'
    | '/plants'
    | '/plants/$plantid/edit'
  id:
    | '__root__'
    | '/'
    | '/catalog/$plantdefid'
    | '/catalog/new'
    | '/plants/$plantid'
    | '/plants/new'
    | '/catalog/'
    | '/plants/'
    | '/plants/$plantid/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CatalogPlantdefidRoute: typeof CatalogPlantdefidRoute
  CatalogNewRoute: typeof CatalogNewRoute
  PlantsPlantidRoute: typeof PlantsPlantidRouteWithChildren
  PlantsNewRoute: typeof PlantsNewRoute
  CatalogIndexRoute: typeof CatalogIndexRoute
  PlantsIndexRoute: typeof PlantsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/': {
      id: '/plants/'
      path: '/plants'
      fullPath: '/plants/'
      preLoaderRoute: typeof PlantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/': {
      id: '/catalog/'
      path: '/catalog'
      fullPath: '/catalog/'
      preLoaderRoute: typeof CatalogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/new': {
      id: '/plants/new'
      path: '/plants/new'
      fullPath: '/plants/new'
      preLoaderRoute: typeof PlantsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/$plantid': {
      id: '/plants/$plantid'
      path: '/plants/$plantid'
      fullPath: '/plants/$plantid'
      preLoaderRoute: typeof PlantsPlantidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/new': {
      id: '/catalog/new'
      path: '/catalog/new'
      fullPath: '/catalog/new'
      preLoaderRoute: typeof CatalogNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog/$plantdefid': {
      id: '/catalog/$plantdefid'
      path: '/catalog/$plantdefid'
      fullPath: '/catalog/$plantdefid'
      preLoaderRoute: typeof CatalogPlantdefidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/$plantid/edit': {
      id: '/plants/$plantid/edit'
      path: '/edit'
      fullPath: '/plants/$plantid/edit'
      preLoaderRoute: typeof PlantsPlantidEditRouteImport
      parentRoute: typeof PlantsPlantidRoute
    }
  }
}

interface PlantsPlantidRouteChildren {
  PlantsPlantidEditRoute: typeof PlantsPlantidEditRoute
}

const PlantsPlantidRouteChildren: PlantsPlantidRouteChildren = {
  PlantsPlantidEditRoute: PlantsPlantidEditRoute,
}

const PlantsPlantidRouteWithChildren = PlantsPlantidRoute._addFileChildren(
  PlantsPlantidRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CatalogPlantdefidRoute: CatalogPlantdefidRoute,
  CatalogNewRoute: CatalogNewRoute,
  PlantsPlantidRoute: PlantsPlantidRouteWithChildren,
  PlantsNewRoute: PlantsNewRoute,
  CatalogIndexRoute: CatalogIndexRoute,
  PlantsIndexRoute: PlantsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
